INSERT INTO "countries" (country_id,country) VALUES (1, 'Ukraine');
INSERT INTO "countries" (country_id,country) VALUES (2, 'Poland');
INSERT INTO "countries" (country_id,country) VALUES (3, 'USA');
INSERT INTO "countries" (country_id,country) VALUES (4, 'United Kingdom');
INSERT INTO "countries" (country_id,country) VALUES (5, 'France');
INSERT INTO "countries" (country_id,country) VALUES (6, 'Germany');
INSERT INTO "countries" (country_id,country) VALUES (7, 'Spain');
INSERT INTO "countries" (country_id,country) VALUES (8, 'Italy');
INSERT INTO "countries" (country_id,country) VALUES (9, 'Canada');
INSERT INTO "countries" (country_id,country) VALUES (10, 'Japan');
